### ISSUE TITLE
Enable Search Engine Optimization (SEO) 

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/change-pioneers#130]
To be able to optimize the website for SEO, we need to prerender all sites.

- It will improve Page Speed & SEO

## Source

- https://angular.io/guide/prerendering

**Comment by GregOnNet** [comment]
We already use the next generation of Angular Components called Stand-Alone Components.

Currently, Server Side Rendering is not supported by Angular.

This will come in the near future.

For now, we need to postpone this issue.

Reference: https://angular.io/guide/universal

**Comment by GregOnNet** [comment]
https://github.com/angular/universal/issues/2906

**Comment by Uli-Armbruster** [comment]
Verstehe ich das richtig: Angular, wie wir es aktuell nutzen, unterstützt kein Server-Side-Rendering. Kam das nicht vor Jahren schon ins Framework rein?

Hinweis: Später gehen wir einen Schritt weiter und implementieren Google for Jobs, siehe

- https://developers.google.com/search/docs/appearance/structured-data/job-posting?hl=de
- - https://www.hrpuls.de/google-for-jobs.html

**Comment by GregOnNet** [comment]
Hi,

Server Side Rendering (SSR) gibt es wirklich seit Jahren.
Das ist Teil des Frameworks: siehe https://github.com/angular/universal/issues/2906.

Wir nutzen bereits eine neuere Version der Component API, die noch nicht mit SSR funktioniert, wird sie aber in Zukunft.
