### ISSUE TITLE
Seite: Geprägt durch Menschen

### ISSUE THREAD

**Issue by Uli-Armbruster** [co-IT/change-pioneers#44]
Entspricht der Karriereseite
Sammlung offener Issues:
- https://github.com/co-IT/change-pioneers/issues/40
- https://github.com/co-IT/change-pioneers/issues/39

Zudem müssen noch die freie Stellen in Recruitee finalisiert werden.

**Comment by GregOnNet** [comment]
@Uli-Armbruster kann dieses Issue geschlossen werden?

**Comment by Uli-Armbruster** [comment]
Ja
