### ISSUE TITLE
Änderung der Schriftgröße durch den Browser zulassen

### ISSUE THREAD

**Issue by FrankStrieter** [co-IT/change-pioneers#59]
Funktioniert zur Zeit noch nicht, da die Standardschriftgröße auf 16px eingestellt ist. durch Änderung auf 100% lässt sich die Browserschriftgröße nutzen.

Dafür ist an einigen Komponenten noch Nacharbeit notwendig.
z.B.
![image](https://user-images.githubusercontent.com/23562240/178702125-ac15d548-ef71-4e4e-825c-61586d4009b6.png)

![image](https://user-images.githubusercontent.com/23562240/178702172-3e151b99-d3b1-46f2-8dfd-3df5c44e7028.png)

![image](https://user-images.githubusercontent.com/23562240/178702409-db2c679d-dde9-4851-ad6f-5a92f83c728f.png)

**Comment by GregOnNet** [comment]
Im neuen Design haben wir Abstufungen in der Schriftgröße berücksichtigt.
